# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/samueldrouin/Development/LabNote/labnote/ui/qt_ui/library.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Library(object):
    def setupUi(self, Library):
        Library.setObjectName("Library")
        Library.resize(700, 400)
        Library.setMinimumSize(QtCore.QSize(700, 400))
        Library.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Library)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(12, 10, 12, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.txt_search = QtWidgets.QLineEdit(Library)
        self.txt_search.setObjectName("txt_search")
        self.horizontalLayout_3.addWidget(self.txt_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.main_frame = QtWidgets.QFrame(Library)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_bookshelf = QtWidgets.QLabel(self.frame)
        self.lbl_bookshelf.setObjectName("lbl_bookshelf")
        self.verticalLayout.addWidget(self.lbl_bookshelf)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_manage = QtWidgets.QPushButton(self.frame)
        self.btn_manage.setText("")
        self.btn_manage.setFlat(True)
        self.btn_manage.setObjectName("btn_manage")
        self.horizontalLayout.addWidget(self.btn_manage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addWidget(self.frame)
        self.detail_layout = QtWidgets.QVBoxLayout()
        self.detail_layout.setContentsMargins(12, 6, 0, 0)
        self.detail_layout.setObjectName("detail_layout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 12, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_key = QtWidgets.QLabel(self.main_frame)
        self.lbl_key.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_key.setFont(font)
        self.lbl_key.setObjectName("lbl_key")
        self.horizontalLayout_5.addWidget(self.lbl_key)
        self.txt_key = QtWidgets.QLineEdit(self.main_frame)
        self.txt_key.setPlaceholderText("")
        self.txt_key.setObjectName("txt_key")
        self.horizontalLayout_5.addWidget(self.txt_key)
        self.comboBox = QtWidgets.QComboBox(self.main_frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.detail_layout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_save = QtWidgets.QPushButton(self.main_frame)
        self.btn_save.setAutoDefault(False)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.detail_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.detail_layout)
        self.verticalLayout_2.addWidget(self.main_frame)

        self.retranslateUi(Library)
        QtCore.QMetaObject.connectSlotsByName(Library)
        Library.setTabOrder(self.txt_key, self.btn_add)
        Library.setTabOrder(self.btn_add, self.txt_search)
        Library.setTabOrder(self.txt_search, self.comboBox)
        Library.setTabOrder(self.comboBox, self.btn_save)
        Library.setTabOrder(self.btn_save, self.btn_manage)

    def retranslateUi(self, Library):
        _translate = QtCore.QCoreApplication.translate
        Library.setWindowTitle(_translate("Library", "Dialog"))
        self.label_2.setText(_translate("Library", "Library"))
        self.txt_search.setPlaceholderText(_translate("Library", "Search"))
        self.lbl_bookshelf.setText(_translate("Library", "Bookshelf"))
        self.btn_add.setText(_translate("Library", "+"))
        self.lbl_key.setText(_translate("Library", "Key "))
        self.comboBox.setItemText(0, _translate("Library", "Article"))
        self.comboBox.setItemText(1, _translate("Library", "Book"))
        self.comboBox.setItemText(2, _translate("Library", "Chapter"))
        self.btn_save.setText(_translate("Library", "Save"))

