# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/samueldrouin/Development/LabNote/labnote/ui/qt_ui/widget/texteditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TextEditor(object):
    def setupUi(self, TextEditor):
        TextEditor.setObjectName("TextEditor")
        TextEditor.resize(797, 474)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(TextEditor)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.icon_frame = QtWidgets.QFrame(TextEditor)
        self.icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_frame.setObjectName("icon_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.icon_frame)
        self.horizontalLayout.setContentsMargins(-1, 6, 12, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_style = QtWidgets.QPushButton(self.icon_frame)
        self.btn_style.setObjectName("btn_style")
        self.horizontalLayout.addWidget(self.btn_style)
        self.widget = QtWidgets.QWidget(self.icon_frame)
        self.widget.setMinimumSize(QtCore.QSize(10, 0))
        self.widget.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.btn_bold = QtWidgets.QPushButton(self.icon_frame)
        self.btn_bold.setCheckable(True)
        self.btn_bold.setObjectName("btn_bold")
        self.horizontalLayout.addWidget(self.btn_bold)
        self.btn_italic = QtWidgets.QPushButton(self.icon_frame)
        self.btn_italic.setCheckable(True)
        self.btn_italic.setObjectName("btn_italic")
        self.horizontalLayout.addWidget(self.btn_italic)
        self.btn_underline = QtWidgets.QPushButton(self.icon_frame)
        self.btn_underline.setCheckable(True)
        self.btn_underline.setObjectName("btn_underline")
        self.horizontalLayout.addWidget(self.btn_underline)
        self.btn_strikethrough = QtWidgets.QPushButton(self.icon_frame)
        self.btn_strikethrough.setCheckable(True)
        self.btn_strikethrough.setObjectName("btn_strikethrough")
        self.horizontalLayout.addWidget(self.btn_strikethrough)
        self.widget_3 = QtWidgets.QWidget(self.icon_frame)
        self.widget_3.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.btn_superscript = QtWidgets.QPushButton(self.icon_frame)
        self.btn_superscript.setText("")
        self.btn_superscript.setCheckable(True)
        self.btn_superscript.setObjectName("btn_superscript")
        self.horizontalLayout.addWidget(self.btn_superscript)
        self.btn_subscript = QtWidgets.QPushButton(self.icon_frame)
        self.btn_subscript.setText("")
        self.btn_subscript.setCheckable(True)
        self.btn_subscript.setObjectName("btn_subscript")
        self.horizontalLayout.addWidget(self.btn_subscript)
        self.widget_2 = QtWidgets.QWidget(self.icon_frame)
        self.widget_2.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.btn_color = QtWidgets.QPushButton(self.icon_frame)
        self.btn_color.setText("")
        self.btn_color.setObjectName("btn_color")
        self.horizontalLayout.addWidget(self.btn_color)
        self.btn_highlight = QtWidgets.QPushButton(self.icon_frame)
        self.btn_highlight.setText("")
        self.btn_highlight.setObjectName("btn_highlight")
        self.horizontalLayout.addWidget(self.btn_highlight)
        self.btn_list = QtWidgets.QPushButton(self.icon_frame)
        self.btn_list.setText("")
        self.btn_list.setCheckable(True)
        self.btn_list.setObjectName("btn_list")
        self.horizontalLayout.addWidget(self.btn_list)
        self.widget_5 = QtWidgets.QWidget(self.icon_frame)
        self.widget_5.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout.addWidget(self.widget_5)
        self.btn_left = QtWidgets.QPushButton(self.icon_frame)
        self.btn_left.setText("")
        self.btn_left.setCheckable(True)
        self.btn_left.setObjectName("btn_left")
        self.horizontalLayout.addWidget(self.btn_left)
        self.btn_center = QtWidgets.QPushButton(self.icon_frame)
        self.btn_center.setText("")
        self.btn_center.setCheckable(True)
        self.btn_center.setObjectName("btn_center")
        self.horizontalLayout.addWidget(self.btn_center)
        self.btn_right = QtWidgets.QPushButton(self.icon_frame)
        self.btn_right.setText("")
        self.btn_right.setCheckable(True)
        self.btn_right.setObjectName("btn_right")
        self.horizontalLayout.addWidget(self.btn_right)
        self.btn_justify = QtWidgets.QPushButton(self.icon_frame)
        self.btn_justify.setText("")
        self.btn_justify.setCheckable(True)
        self.btn_justify.setObjectName("btn_justify")
        self.horizontalLayout.addWidget(self.btn_justify)
        self.widget_6 = QtWidgets.QWidget(self.icon_frame)
        self.widget_6.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_6.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout.addWidget(self.widget_6)
        self.txt_width = QtWidgets.QLineEdit(self.icon_frame)
        self.txt_width.setMinimumSize(QtCore.QSize(40, 0))
        self.txt_width.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_width.setObjectName("txt_width")
        self.horizontalLayout.addWidget(self.txt_width)
        self.txt_height = QtWidgets.QLineEdit(self.icon_frame)
        self.txt_height.setMinimumSize(QtCore.QSize(40, 0))
        self.txt_height.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_height.setObjectName("txt_height")
        self.horizontalLayout.addWidget(self.txt_height)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.icon_frame)
        self.title_layout = QtWidgets.QHBoxLayout()
        self.title_layout.setObjectName("title_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(TextEditor)
        self.widget_4.setStyleSheet("QWidget { background-color: white; }")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_created = QtWidgets.QLabel(self.widget_4)
        self.lbl_created.setMinimumSize(QtCore.QSize(150, 0))
        self.lbl_created.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_created.setStyleSheet("color: rgb(96, 96, 96)")
        self.lbl_created.setText("")
        self.lbl_created.setObjectName("lbl_created")
        self.verticalLayout_5.addWidget(self.lbl_created)
        self.lbl_updated = QtWidgets.QLabel(self.widget_4)
        self.lbl_updated.setMinimumSize(QtCore.QSize(150, 0))
        self.lbl_updated.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_updated.setStyleSheet("color: rgb(96, 96, 96)")
        self.lbl_updated.setText("")
        self.lbl_updated.setObjectName("lbl_updated")
        self.verticalLayout_5.addWidget(self.lbl_updated)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.title_layout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.title_layout)
        self.save_layout = QtWidgets.QHBoxLayout()
        self.save_layout.setContentsMargins(6, 6, 6, 6)
        self.save_layout.setObjectName("save_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.save_layout.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(TextEditor)
        self.btn_save.setObjectName("btn_save")
        self.save_layout.addWidget(self.btn_save)
        self.verticalLayout_4.addLayout(self.save_layout)

        self.retranslateUi(TextEditor)
        QtCore.QMetaObject.connectSlotsByName(TextEditor)

    def retranslateUi(self, TextEditor):
        _translate = QtCore.QCoreApplication.translate
        TextEditor.setWindowTitle(_translate("TextEditor", "Form"))
        self.btn_style.setToolTip(_translate("TextEditor", "Text format"))
        self.btn_style.setText(_translate("TextEditor", "§"))
        self.btn_bold.setToolTip(_translate("TextEditor", "Bold"))
        self.btn_bold.setText(_translate("TextEditor", "B"))
        self.btn_italic.setToolTip(_translate("TextEditor", "Italic"))
        self.btn_italic.setText(_translate("TextEditor", "I"))
        self.btn_underline.setToolTip(_translate("TextEditor", "Underline"))
        self.btn_underline.setText(_translate("TextEditor", "U"))
        self.btn_strikethrough.setToolTip(_translate("TextEditor", "Strikethrough"))
        self.btn_strikethrough.setText(_translate("TextEditor", "abc"))
        self.btn_superscript.setToolTip(_translate("TextEditor", "Superscript"))
        self.btn_subscript.setToolTip(_translate("TextEditor", "Subscript"))
        self.btn_color.setToolTip(_translate("TextEditor", "Text color"))
        self.btn_highlight.setToolTip(_translate("TextEditor", "Highlight color"))
        self.btn_list.setToolTip(_translate("TextEditor", "List type"))
        self.btn_left.setToolTip(_translate("TextEditor", "Align Left"))
        self.btn_center.setToolTip(_translate("TextEditor", "Align Center"))
        self.btn_right.setToolTip(_translate("TextEditor", "Align Right"))
        self.btn_justify.setToolTip(_translate("TextEditor", "Align Justify"))
        self.txt_width.setPlaceholderText(_translate("TextEditor", "0"))
        self.txt_height.setPlaceholderText(_translate("TextEditor", "0"))
        self.btn_save.setText(_translate("TextEditor", "Save"))

