# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/samueldrouin/Development/LabNote/labnote/ui/qt_ui/widget/texteditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TextEditor(object):
    def setupUi(self, TextEditor):
        TextEditor.setObjectName("TextEditor")
        TextEditor.resize(704, 461)
        self.verticalLayout = QtWidgets.QVBoxLayout(TextEditor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(TextEditor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon_frame = QtWidgets.QFrame(self.frame)
        self.icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_frame.setObjectName("icon_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.icon_frame)
        self.horizontalLayout.setContentsMargins(-1, 6, 12, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_style = QtWidgets.QPushButton(self.icon_frame)
        self.btn_style.setObjectName("btn_style")
        self.horizontalLayout.addWidget(self.btn_style)
        self.widget = QtWidgets.QWidget(self.icon_frame)
        self.widget.setMinimumSize(QtCore.QSize(10, 0))
        self.widget.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.btn_bold = QtWidgets.QPushButton(self.icon_frame)
        self.btn_bold.setCheckable(True)
        self.btn_bold.setObjectName("btn_bold")
        self.horizontalLayout.addWidget(self.btn_bold)
        self.btn_italic = QtWidgets.QPushButton(self.icon_frame)
        self.btn_italic.setCheckable(True)
        self.btn_italic.setObjectName("btn_italic")
        self.horizontalLayout.addWidget(self.btn_italic)
        self.btn_underline = QtWidgets.QPushButton(self.icon_frame)
        self.btn_underline.setCheckable(True)
        self.btn_underline.setObjectName("btn_underline")
        self.horizontalLayout.addWidget(self.btn_underline)
        self.btn_strikethrough = QtWidgets.QPushButton(self.icon_frame)
        self.btn_strikethrough.setCheckable(True)
        self.btn_strikethrough.setObjectName("btn_strikethrough")
        self.horizontalLayout.addWidget(self.btn_strikethrough)
        self.widget_3 = QtWidgets.QWidget(self.icon_frame)
        self.widget_3.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.btn_superscript = QtWidgets.QPushButton(self.icon_frame)
        self.btn_superscript.setText("")
        self.btn_superscript.setCheckable(True)
        self.btn_superscript.setObjectName("btn_superscript")
        self.horizontalLayout.addWidget(self.btn_superscript)
        self.btn_subscript = QtWidgets.QPushButton(self.icon_frame)
        self.btn_subscript.setText("")
        self.btn_subscript.setCheckable(True)
        self.btn_subscript.setObjectName("btn_subscript")
        self.horizontalLayout.addWidget(self.btn_subscript)
        self.widget_2 = QtWidgets.QWidget(self.icon_frame)
        self.widget_2.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.btn_color = QtWidgets.QPushButton(self.icon_frame)
        self.btn_color.setText("")
        self.btn_color.setObjectName("btn_color")
        self.horizontalLayout.addWidget(self.btn_color)
        self.btn_highlight = QtWidgets.QPushButton(self.icon_frame)
        self.btn_highlight.setText("")
        self.btn_highlight.setObjectName("btn_highlight")
        self.horizontalLayout.addWidget(self.btn_highlight)
        self.btn_list = QtWidgets.QPushButton(self.icon_frame)
        self.btn_list.setText("")
        self.btn_list.setCheckable(True)
        self.btn_list.setObjectName("btn_list")
        self.horizontalLayout.addWidget(self.btn_list)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.icon_frame)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_title = QtWidgets.QLineEdit(self.frame_2)
        self.txt_title.setObjectName("txt_title")
        self.verticalLayout_2.addWidget(self.txt_title)
        self.lbl_date = QtWidgets.QLabel(self.frame_2)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout_2.addWidget(self.lbl_date)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(TextEditor)
        QtCore.QMetaObject.connectSlotsByName(TextEditor)

    def retranslateUi(self, TextEditor):
        _translate = QtCore.QCoreApplication.translate
        TextEditor.setWindowTitle(_translate("TextEditor", "Form"))
        self.btn_style.setToolTip(_translate("TextEditor", "Text format"))
        self.btn_style.setText(_translate("TextEditor", "§"))
        self.btn_bold.setToolTip(_translate("TextEditor", "Bold"))
        self.btn_bold.setText(_translate("TextEditor", "B"))
        self.btn_italic.setToolTip(_translate("TextEditor", "Italic"))
        self.btn_italic.setText(_translate("TextEditor", "I"))
        self.btn_underline.setToolTip(_translate("TextEditor", "Underline"))
        self.btn_underline.setText(_translate("TextEditor", "U"))
        self.btn_strikethrough.setToolTip(_translate("TextEditor", "Strikethrough"))
        self.btn_strikethrough.setText(_translate("TextEditor", "abc"))
        self.btn_superscript.setToolTip(_translate("TextEditor", "Superscript"))
        self.btn_subscript.setToolTip(_translate("TextEditor", "Subscript"))
        self.btn_color.setToolTip(_translate("TextEditor", "Text color"))
        self.btn_highlight.setToolTip(_translate("TextEditor", "Highlight color"))
        self.btn_list.setToolTip(_translate("TextEditor", "List type"))
        self.lbl_date.setText(_translate("TextEditor", "date"))

